import type { Metadata } from "next";
import { Poppins, Manrope } from "next/font/google";
import Footer from "./components/footer";
import Nav from "./components/nav";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "miyuki nozawa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className="bg-base">
      <body className={`${poppins.className} max-w-screen-2xl min-h-screen mx-auto bg-base`}>
        <Nav />
        {children}
        <Footer />
      </body>
    </html>
  );
}
