import type { Metadata } from "next";
import { Inter, Manrope, Poppins } from "next/font/google";
import Nav from "@/app/components/nav";
import "./globals.css";

const poppins = Poppins({
  subsets: ["latin"],
  variable: "--font-poppins",
  weight: ["300", "400", "500", "600"],
});

const manrope = Manrope({
  subsets: ["latin"],
  variable: "--font-manrope",
  weight: ["400", "500", "600", "700"],
});

const inter = Inter({
  subsets: ["latin"],
  variable: "--font-inter",
  weight: ["400", "500", "600", "700"],
});

export const metadata: Metadata = {
  title: "miyuki nozawa",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`
          ${poppins.className}
          ${manrope.variable}
          ${inter.variable}
          max-w-[1440px]
          mx-auto
          bg-white
          text-black
          tracking-[.02em]
          cursor-default
        `}
      >
        <Nav />
        {/* spacer */}
        <div className="bg-base h-[19.2vw] lg:h-[192px]"></div>
        {children}
      </body>
    </html>
  );
}
